language: node_js
node_js:
  - "10.15.3"

branches:
  only:
    - master
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
    - node_modules

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm ci
script:
  - ng test --watch=false --no-progress --browsers=ChromeHeadlessCI
  - ng build --prod


after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change